### ISSUE TITLE
high memory usage

### ISSUE THREAD

**Issue by ags799** [chriskol/Desktop-Google-Keep-OSX#10]
This app consumes ~340 MB of memory on my machine. To compare, Google Chrome with a Google Keep tab open consumes ~150 MB. It seems this app is consuming more memory than it should.

**Comment by ags799** [comment]
Love the app by the way 😍

**Comment by chriskol** [comment]
I think this is probably an issue with Macgap but am open to thoughts otherwise.  Did you download a binary or compile yourself?

**Comment by ags799** [comment]
downloaded a binary

**Comment by ags799** [comment]
i took a look at chrome's task manager, turns out keep just consumes a lot:
<img width="788" alt="screen shot 2018-03-31 at 6 37 35 pm" src="https://user-images.githubusercontent.com/2957581/38168479-bfadddb0-3512-11e8-9612-4981647c61db.png">
maybe there's not much we can do 😞

**Comment by chriskol** [comment]
Keep gonna keep I suppose.
