### ISSUE TITLE
App window has double toolbar

### ISSUE THREAD

**Issue by stevekroodsma** [chriskol/Desktop-Google-Keep-OSX#16]
Hi there. For the last two months my app window has had an extra toolbar. Not sure if it's a MacGap thing or if I employed a keyboard shortcut unknowingly, but I would love to get rid of it. Any ideas?

<img width="369" alt="Screen Shot 2020-01-29 at 12 41 27 PM" src="https://user-images.githubusercontent.com/20461543/73386834-236b0d00-4295-11ea-9117-45c3a5f9ea81.png">

**Comment by chriskol** [comment]
That's bizarre.  It's definitely not happening on my build though I didn't build on Catalina but on an older OSX...so maybe that's causing it?  Long shot but maybe download one of the binaries on the release page that I built on my system and see if the issue persists?

**Comment by stevekroodsma** [comment]
So strange, I'm still on Sierra. Unfortunately I'm too much of a novice to know how to install from a binary, but I'll be sure to post back here if I ever figure out what caused it. Thanks for the reply!

**Comment by chriskol** [comment]
Binary would be downloading from the release page and using the already packaged .app file.  This can cause issues as basically you're getting an app that's built based on my system and it can cause problems if it's just transfered to yours.  The best bet to avoid issues is to build it yourself using the instructions.

HOWEVER, you might be able to have some luck if you you download one of the older releases and try that.  Most of the changes are outlined in the change logs and are mostly cosmetic (Changing icon, changing title name, etc.) so you might have some luck for functionality purposes on an older version.

**Comment by stevekroodsma** [comment]
Figured it out! I just went to View>Show Tab Bar. Duh.
