### ISSUE TITLE
Broken on Catalina

### ISSUE THREAD

**Issue by one000mph** [chriskol/Desktop-Google-Keep-OSX#17]
Looks like this is incompatible with Catalina. It opens but I cannot edit or make new notes.

**Comment by chriskol** [comment]
Hey Heather,

Did you build yourself or download a binary from the release page? I think
I included a warning that using the binaries can cause issues and you
really should build yourself. I'm on Catalina and using a version I built
on el Capitan just fine. Can you confirm how you started using it and we
can go from there?

**Comment by one000mph** [comment]
OK I downloaded again and looks fine now. thanks!
