### ISSUE TITLE
Hey! Love the app, want smaller fonts

### ISSUE THREAD

**Issue by sming** [chriskol/Desktop-Google-Keep-OSX#18]
Hi Chris,

I love the keep app, it saves a bunch of tab-hunting. I'd like smaller fonts but can't find the MacGap docco on how to do that - could you obliged?

Many thanks, Pete

**Comment by chriskol** [comment]
Hmmm.  There might be a way to do that if it's not in the MacGap doc.  But maybe finding a way to enable that on that particular repo would be a good starting point.

**Comment by sming** [comment]
> Hmmm. There might be a way to do that if it's not in the MacGap doc. But maybe finding a way to enable that on that particular repo would be a good starting point.

Hi Chris (presumably),

no worries, I discovered (don't know how long it's been there...) the : `... →  More tools → Create shortcut` function, which basically wraps a page in an app that resides (on OS X) in `/Applications/Chrome Apps.localized/`. Who'da thunk.

Cheers,
Pete
