### ISSUE TITLE
This project vs native chrome extension

### ISSUE THREAD

**Issue by simplenotezy** [chriskol/Desktop-Google-Keep-OSX#4]
I am curious whether this is any different from https://chrome.google.com/webstore/detail/google-keep-notes-and-lis/hmjkmjkepdijhoojdojkdfohbdgmmhki/related?

Source: http://www.rawinfopages.com/mac/content/add-google-keep-notes-dock-os-x

**Comment by chriskol** [comment]
I'm not sure.  I don't use Chrome but this might do a similar thing once you use the 'keep in dock' option after opening it in Chrome?

**Comment by Palivec** [comment]
Well their app cant run without Chrome running too, its not standalone.
