### ISSUE TITLE
uninstall

### ISSUE THREAD

**Issue by adriancostash** [chriskol/Desktop-Google-Keep-OSX#6]
Hi, I uninstalled your app for I decided to switch to the Google Chrome version and now whenever i click the app in the google browser it still opens as a standalone app, as if as your app. 

And it still appears in Launchpad, although not in the Applications folder. What can I do to switch to the default behaviour?

Thanks for your help!

**Comment by chriskol** [comment]
I don't think I understand the first part.  It should look the same because my app basically opens up a browser window standalone.  Did it look different before?  When you say you 'click the app in the google browser' what does that mean?  I thought you uninstalled the app?

I uninstalled and saw indeed it still appears in Launchpad.  It looks like this is an issue with Launchpad though as a quick google search shows [many other people having this issue](https://www.google.com/search?q=apps+still+appear+in+launchpad+after+delete&ie=utf-8&oe=utf-8). For me, it disappeared when I restarted my computer.

**Comment by adriancostash** [comment]
Hi, sorry for bothering you. I am a moron. It turn out that is the appropriate behaviour flr the Google app. Which is weird, but hey, they know better. 
My best and thank you for your time


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Christopher Kolmatycki <notifications@github.com> Date: 10/24/17  20:14  (GMT+02:00) To: chriskol/Desktop-Google-Keep-OSX <Desktop-Google-Keep-OSX@noreply.github.com> Cc: adriancostash <johnadriancostache@gmail.com>, Author <author@noreply.github.com> Subject: Re: [chriskol/Desktop-Google-Keep-OSX] uninstall (#6) 
I don't think I understand the first part.  It should look the same because my app basically opens up a browser window standalone.  Did it look different before?  When you say you 'click the app in the google browser' what does that mean?  I thought you uninstalled the app?
I uninstalled and saw indeed it still appears in Launchpad.  It looks like this is an issue with Launchpad though as a quick google search shows many other people having this issue. For me, it disappeared when I restarted my computer.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/chriskol/Desktop-Google-Keep-OSX","title":"chriskol/Desktop-Google-Keep-OSX","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/chriskol/Desktop-Google-Keep-OSX"}},"updates":{"snippets":[{"icon":"PERSON","message":"@chriskol in #6: I don't think I understand the first part.  It should look the same because my app basically opens up a browser window standalone.  Did it look different before?  When you say you 'click the app in the google browser' what does that mean?  I thought you uninstalled the app?\r\n\r\nI uninstalled and saw indeed it still appears in Launchpad.  It looks like this is an issue with Launchpad though as a quick google search shows [many other people having this issue](https://www.google.com/search?q=apps+still+appear+in+launchpad+after+delete\u0026ie=utf-8\u0026oe=utf-8). For me, it disappeared when I restarted my computer."}],"action":{"name":"View Issue","url":"https://github.com/chriskol/Desktop-Google-Keep-OSX/issues/6#issuecomment-339064514"}}}

**Comment by chriskol** [comment]
No worries!  Glad your problems were resolved :)
