### ISSUE TITLE
display issues

### ISSUE THREAD

**Issue by chichaz** [chriskol/Desktop-Google-Keep-OSX#7]
Text is bunching up, displaying all lines of notes on one line instead of multiple lines. I'm running Yosemite. Can send screenshots via email if that would be helpful.

**Comment by chriskol** [comment]
I guess posting screenshots would help.  Not sure what the cause would be...

**Comment by chichaz** [comment]
Here's the screen shot. Hope this helps. The app worked perfectly until a
couple of updates ago.
Cheers,
-Charlie

**Comment by chriskol** [comment]
No screen shot attached :(
I don't think you can do screenshots from email.

**Comment by chichaz** [comment]
![screen shot 2017-11-15 at 6 56 53 pm](https://user-images.githubusercontent.com/33788726/33774657-9dab3858-dc01-11e7-8677-8cd491460daa.png)

**Comment by chriskol** [comment]
That is not at all what I see...

Anyone else getting something similar?

No idea what would be causing this.  Maybe WebViews on your system isn't working?  You might need Xcode?  Maybe it's a Yosemite issue?  I built this on Mavericks and it was working and am now on High Sierra so unsure myself :/

**Comment by chichaz** [comment]
Is the previous version of the app available?

**Comment by chriskol** [comment]
You can see all releases of the app [here](https://github.com/chriskol/Desktop-Google-Keep-OSX/releases).  Right now there's just the current one and the initial one.
